### PR TITLE
Laravel 6.x support

### PR DESCRIPTION
**Pull request by vokamut**

### CODE REVIEW

**Comment by bubba-h57** [comment]
Good call, but actually, the newest versions only support `^5.4|^6.0` ... would you mind updating for that and then I'll merge?

**Comment by vokamut** [comment]
Laravel and its other first-party packages follow Semantic Versioning.
https://laravel.com/docs/6.x/releases

**Comment by bubba-h57** [comment]
Yes it does. Yet, I'm not sure what your point is?

**Comment by vokamut** [comment]
I change versions

**Comment by bubba-h57** [comment]
Thanks!

**Pull request merged**
